### ISSUE TITLE
routing-icon.png doesn't exist for leaflet-routing-collapse-btn

### ISSUE THREAD

**Issue by bwainstock** [mapzen/lrm-mapzen#32]
The collapsible button icon doesn't exist in the project files.  routing-icon.png is not distributed.

```css
.leaflet-routing-container-hide .leaflet-routing-collapse-btn {
    position: relative;
    left: 4px;
    top: 4px;
    display: block;
    width: 26px;
    height: 23px;
    background-image: url('routing-icon.png');
}
```
